name: Job Sequential
on:
 workflow_dispatch


jobs:
  job1:
    runs-on: ubuntu-latest
    run: sleep 2
  job2:
    runs-on: ubuntu-latest
    run: sleep 2
  job3:
    runs-on: ubuntu-latest
    run: sleep 2



