name: Matrix Execution
on:
  workflow_dispatch
jobs:
  matrix_example:
    runs-on: ubuntu:latest
    strategy:
      matrix:
        version: [18, 19, 24]


    steps:
      - name: Checkout
        uses: actions/checkout@v4



      - name: Install Nodejs
        uses: actions/setup-node@v6    
        with:
          node-version: ${{ matrix.version }}



     