name: show_variables

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose Environment'
        required: true
        default: 'test'
        type: choice
        options:
          - dev
          - prod
          - test


      version:
        description: 'App Version'
        required: true
        default: 'v1.0.0'

env:
 Global_Env: "One Tier"        



jobs:
  job1:
     runs-on: ubuntu-latest
     env:
      JOB1_ENV: "gattu"
     steps:
       - name: Show the inputs
         run: |
          echo "Environment type: ${{inputs.environment}}"
          echo "Application Version : ${{inputs.version}}"

       - name: Global_Variables
         run: |
          echo "Global env: $Global_Env" 
       - name: Job1_environment
         run: |
          echo "Job env: $JOB1_ENV"    
          



  job2:
     runs-on: ubuntu-latest
     env:
      JOB2_ENV: "Shimla"
     steps:
       - name: Job_2 environment
         run: |
          echo "Job2 environment: $JOB2_ENV"
  job3:
     runs-on: ubuntu-latest
     steps:
       - name: Variables and secrets
         run: |
          echo "git Variables: ${{vars.FIRST_VARIABLE}}"
          echo "git Secrets: ${{secrets.FIRST_SECRET}}"
        
        

          
    